### ISSUE TITLE
Failed to install on Windows 7 32bit (GHC 7.10.3)

### ISSUE THREAD

**Issue by yejianhui** [lehins/hip#1]
Building hip-1.0.0.0...
Preprocessing library hip-1.0.0.0...
[ 1 of 27] Compiling Graphics.Image.IO.Base ( src\Graphics\Image\IO\Base.hs, dist\build\Graphics\Image\IO\Base.o )
[ 2 of 27] Compiling Graphics.Image.Interface ( src\Graphics\Image\Interface.hs, dist\build\Graphics\Image\Interface.o )

src\Graphics\Image\Interface.hs:16:1: Warning:
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()

src\Graphics\Image\Interface.hs:19:1: Warning:
    The import of ‘Data.Foldable’ is redundant
      except perhaps to import instances from ‘Data.Foldable’
    To import instances alone, use: import Data.Foldable()
[ 3 of 27] Compiling Graphics.Image.ColorSpace.Luma ( src\Graphics\Image\ColorSpace\Luma.hs, dist\build\Graphics\Image\ColorSpace\Luma.o )

src\Graphics\Image\ColorSpace\Luma.hs:11:1: Warning:
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
[ 4 of 27] Compiling Graphics.Image.ColorSpace.RGB ( src\Graphics\Image\ColorSpace\RGB.hs, dist\build\Graphics\Image\ColorSpace\RGB.o )

src\Graphics\Image\ColorSpace\RGB.hs:11:1: Warning:
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
[ 5 of 27] Compiling Graphics.Image.ColorSpace.HSI ( src\Graphics\Image\ColorSpace\HSI.hs, dist\build\Graphics\Image\ColorSpace\HSI.o )

src\Graphics\Image\ColorSpace\HSI.hs:11:1: Warning:
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
[ 6 of 27] Compiling Graphics.Image.ColorSpace.CMYK ( src\Graphics\Image\ColorSpace\CMYK.hs, dist\build\Graphics\Image\ColorSpace\CMYK.o )

src\Graphics\Image\ColorSpace\CMYK.hs:11:1: Warning:
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
[ 7 of 27] Compiling Graphics.Image.ColorSpace.YCbCr ( src\Graphics\Image\ColorSpace\YCbCr.hs, dist\build\Graphics\Image\ColorSpace\YCbCr.o )

src\Graphics\Image\ColorSpace\YCbCr.hs:11:1: Warning:
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
[ 8 of 27] Compiling Graphics.Image.ColorSpace.Gray ( src\Graphics\Image\ColorSpace\Gray.hs, dist\build\Graphics\Image\ColorSpace\Gray.o )

src\Graphics\Image\ColorSpace\Gray.hs:11:1: Warning:
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
[ 9 of 27] Compiling Graphics.Image.ColorSpace.Complex ( src\Graphics\Image\ColorSpace\Complex.hs, dist\build\Graphics\Image\ColorSpace\Complex.o )
[10 of 27] Compiling Graphics.Image.ColorSpace.Binary ( src\Graphics\Image\ColorSpace\Binary.hs, dist\build\Graphics\Image\ColorSpace\Binary.o )

src\Graphics\Image\ColorSpace\Binary.hs:11:1: Warning:
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
[11 of 27] Compiling Graphics.Image.Interface.Vector.Unboxed ( src\Graphics\Image\Interface\Vector\Unboxed.hs, dist\build\Graphics\Image\Interface\Vector\Unboxed.o )

src\Graphics\Image\Interface\Vector\Unboxed.hs:241:9: Warning:
    Variable ‘cs’ is implicitly quantified due to a context
    Use explicit forall syntax instead.
    This will become an error in GHC 7.12.
    In the type ‘(ColorSpace cs, Unbox (PixelElt cs e)) =>
                 (Pixel cs e) -> (PixelElt cs e)’
    In a Template-Haskell quoted type

src\Graphics\Image\Interface\Vector\Unboxed.hs:241:9: Warning:
    Variable ‘e’ is implicitly quantified due to a context
    Use explicit forall syntax instead.
    This will become an error in GHC 7.12.
    In the type ‘(ColorSpace cs, Unbox (PixelElt cs e)) =>
                 (Pixel cs e) -> (PixelElt cs e)’
    In a Template-Haskell quoted type
[12 of 27] Compiling Graphics.Image.Interface.Repa.Internal ( src\Graphics\Image\Interface\Repa\Internal.hs, dist\build\Graphics\Image\Interface\Repa\Internal.o )

src\Graphics\Image\Interface\Repa\Internal.hs:149:47:
    Ambiguous occurrence ‘traverse’
    It could refer to either ‘Prelude.traverse’,
                             imported from ‘Prelude’ at src\Graphics\Image\Interface\Repa\Internal.hs:10:1-69
                             (and originally defined in ‘Data.Traversable’)
                          or ‘Graphics.Image.Interface.traverse’,
                             imported from ‘Graphics.Image.Interface’ at src\Graphics\Image\Interface\Repa\Internal.hs:12:1-31
                             (and originally defined
                                at src\Graphics\Image\Interface.hs:(166,3)-(176,28))

src\Graphics\Image\Interface\Repa\Internal.hs:196:56:
    Ambiguous occurrence ‘traverse’
    It could refer to either ‘Prelude.traverse’,
                             imported from ‘Prelude’ at src\Graphics\Image\Interface\Repa\Internal.hs:10:1-69
                             (and originally defined in ‘Data.Traversable’)
                          or ‘Graphics.Image.Interface.traverse’,
                             imported from ‘Graphics.Image.Interface’ at src\Graphics\Image\Interface\Repa\Internal.hs:12:1-31
                             (and originally defined
                                at src\Graphics\Image\Interface.hs:(166,3)-(176,28))

**Comment by lehins** [comment]
@yejianhui thank you for reporting this issue. I will soon release fixed version on hackage.
