### ISSUE TITLE
RTS detects <<loop>> when writing image

### ISSUE THREAD

**Issue by darcykimball** [lehins/hip#12]
Processing an image with `thresholdWith` and `normalize` (dunno if they have anything to do with this behavior, though), then attempting to save the result using `writeImageExact` results in a \<\<loop\>\> exception. Strangely, it works just fine in ghci, but the compiled version emits the exception. I was trying to compile with -prof to get a stacktrace, etc. but there were issues with stack, so unfortunately I can't offer much more info ATM.

This is the best I could do for a minimal reproduction:
(this is in a stack project; app/Main.hs just contains main = someFunc)

```
import Graphics.Image as I


someFunc :: IO ()
someFunc = do
  img <- readImageY VS "coins.png"
  let processedImg = processImg img
  writeImageExact PNG [] "processed.png" processedImg


processImg :: Image VS Y Double -> Image VS X Bit
processImg = thresholdWith (PixelY (> 0.5)) . normalize

```
`
Here's the input image (I did try other images; same result):
![coins](https://user-images.githubusercontent.com/12655595/33223146-f4457af2-d111-11e7-9cf7-417a9ecfa50b.png)

and here's my cabal/stack cfg files, if that helps

hip-test.cabal:
```
name:                hip-test
version:             0.1.0.0
-- synopsis:
-- description:
homepage:            https://github.com/githubuser/hip-test#readme
license:             BSD3
license-file:        LICENSE
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
build-type:          Simple
extra-source-files:  README.md
cabal-version:       >=1.10

library
  hs-source-dirs:      src
  exposed-modules:     Lib
  build-depends:       base >= 4.7 && < 5
                     , hip
  default-language:    Haskell2010

executable hip-test-exe
  hs-source-dirs:      app
  main-is:             Main.hs
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  build-depends:       base
                     , hip-test
  default-language:    Haskell2010

test-suite hip-test-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             Spec.hs
  build-depends:       base
                     , hip-test
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010

source-repository head
  type:     git
  location: https://github.com/githubuser/hip-test
```

stack.yaml:
```
flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- hip-1.5.3.0
- repa-3.4.1.3
resolver: lts-9.14
```

**Comment by lehins** [comment]
It looks like you are hitting this GHC bug: https://ghc.haskell.org/trac/ghc/ticket/13429
Unfortunately there is no workaround for it a the moment that I know of, except switching to GHC-8.2.
Try switching to a nightly snapshot and see if it fixes the problem.
I am planning a major rewrite of this library once I'll finish work on [massiv](https://github.com/lehins/massiv), consequently dropping support of repa. Because of this I have no plans on trying to work around this GHC bug at the moment.
Please close this issue if you can confirm using newer ghc prevents this `<<loop>>` from happening.

**Comment by darcykimball** [comment]
Thanks for the reply! Switching to GHC 8.2 fixes everything, though I hope the next person who runs into this will think of that faster than I found out.
