### ISSUE TITLE
cannot save loaded images

### ISSUE THREAD

**Issue by hgeg** [lehins/hip#2]
I was meddling with the library before I use it in my project, and I cannot manage to create a very simple program that reads an image, perform some manipulations and saves it. I even failed to do a barebones task which is:

    img <- I.readImageRGBA "grad_color.png"
    I.writeImage "img.png" img

that gives the following error:

```
<interactive>:34:1:
    No instance for (hip-1.0.1:Graphics.Image.IO.Base.Writable
                       (Image VU RGBA Double)
                       hip-1.0.1:Graphics.Image.IO.External.JuicyPixels.JPG)
      arising from a use of `I.writeImage'
    Possible fix:
      add an instance declaration for
      (hip-1.0.1:Graphics.Image.IO.Base.Writable
         (Image VU RGBA Double)
         hip-1.0.1:Graphics.Image.IO.External.JuicyPixels.JPG)
    In the expression: I.writeImage "img.png" img
    In an e<interactive>:34:1:
    No instance for (hip-1.0.1:Graphics.Image.IO.Base.Writable
                       (Image VU RGBA Double)
                       hip-1.0.1:Graphics.Image.IO.External.JuicyPixels.JPG)
      arising from a use of `I.writeImage'
    Possible fix:
      add an instance declaration for
      (hip-1.0.1:Graphics.Image.IO.Base.Writable
         (Image VU RGBA Double)
         hip-1.0.1:Graphics.Image.IO.External.JuicyPixels.JPG)
    In the expression: I.writeImage "img.png" img
    In an equation for `it': it = I.writeImage "img.png" img
```

As you can probably infer from the above example the following code, provided in the documentation works perfectly:

```
let grad_color = I.makeImage (200, 200) 
    (\(i, j) -> PixelRGB (fromIntegral i) (fromIntegral j) (fromIntegral (i + j)))
I.writeImage "grad_color.png" grad_color
```

And yet, when I compared the types, there seems to be no difference:

```
> :t img
img :: Image VU RGBA Double
> :t grad_color
grad_color :: Image VU RGB Double
```
Can you help me about this problem? Am I making an obvious mistake here? At the very least I appreciate a small sample code of read/write operation.

Thank you.

**Comment by lehins** [comment]
Thank you for reporting this, I actually fixed this issue yesterday. It only affects writing `RGBA` images, and had to do with lack of instance for JPG format.
I will make a new release that includes this fix probably later on today.
For now you can save `RGBA` image using `writeImageExact`, like so:

    img <- I.readImageRGBA "grad_color.png"
    I.writeImageExact PNG [] "img.png" img

**Comment by hgeg** [comment]
OK, thanks.

**Comment by lehins** [comment]
Oh and just to let you know, there is a slight difference:

> :t img
img :: Image VU **RGBA** Double
> :t grad_color
grad_color :: Image VU **RGB** Double

`img` has RGB with alpha, where `grad_image` is pure `RGB`, that is there reason, why documentation example works and the one you tried didn't (it was read as RGBA): 

> img <- I.readImage**RGBA** "grad_color.png"

**Comment by lehins** [comment]
@hgeg, the new version is up on hackage. 
Feel free to send me any questions. This is a very fresh library, so any feedback is appreciated.
