### ISSUE TITLE
Implement Noise addition in images

### ISSUE THREAD

**Issue by khilanravani** [lehins/hip#21]
@lehins @alpmestan Sir, while testing my previous algorithm (Gaussian smoothing), I realized that hip is missing some functions of adding noise to images (Kindly correct me if I'm wrong). I feel that noise addition functions are a vital base for many other image processing algorithms and are required especially for testing algorithms related to testing and processing of Satellite data. So, I'm planning to maybe add a few of those functions (salt & pepper noise, gaussian noise etc) first before proceeding to other algorithms. I would like to request your views on this matter and kindly tell me if you would like these additions in HIP. Also, if I'm not wrong there are a few more basic filters (mean, some frequency filters etc.) which are missing and I plan to implement them first too.

**Comment by lehins** [comment]
@khilanravani Sounds good with me.

**Comment by khilanravani** [comment]
@lehins Thank u sir. So, I guess I'll get started with the filters and noise addition functions then :-)

**Comment by khilanravani** [comment]
@lehins Sir, for noise addition algos, I need some random generation. So, is it alright if I add 'random' package to the Build-depends in cabal file?

**Comment by lehins** [comment]
@khilanravani Yeah, `random` is good for those purposes.

**Comment by khilanravani** [comment]
@lehins Salt and pepper noise implemented sir. Kindly review it.
