### ISSUE TITLE
Bicubic interpolation suppport

### ISSUE THREAD

**Issue by kirisaki** [lehins/hip#36]
I would be grateful if you could support bicubic interpolation.
If you were not going to implement it, I plan to do it and send a PR. How about it?

**Comment by lehins** [comment]
I'd love to add bicubic interpolation, but I am not planning to work on it in near future, so if you up for a challenge I'll be happy to accept a PR. You can try to follow the example of bilinear interpolation that is already available in HIP.

**Comment by lehins** [comment]
Implemented in #37 thanks again @kirisaki
