### ISSUE TITLE
some reason `fromRepa...` functions are gone?

### ISSUE THREAD

**Issue by silky** [lehins/hip#6]
i'm trying to convert an image to a repa array, do things to it, and convert back, but it looks like the backwards-converting functions are commented out? am i missing some simple way of doing this?

**Comment by lehins** [comment]
I recently changed underlying implementation for image representations and somehow forgot to get those functions updated. My apologies for that. I will be making a new release in a few hours and those function will be brought back to life.
Thank you for reporting.

**Comment by lehins** [comment]
Fix for this issue is now on Hackage.
