### ISSUE TITLE
superimpose traverses over both images; can be very slow

### ISSUE THREAD

**Issue by silky** [lehins/hip#7]
suppose you are `superimpose`ing a small image (50,50) into a (1000,1000) image. it seems to me that this function will walk across the entire (1000,1000) dim picture, when it feels like it doesn't need to. 

this is slower than it needs to be, i think. can we perhaps speed up this function by avoiding this larger traversal?

any thoughts?

**Comment by lehins** [comment]
What `superimpose` will do is walk across (1000, 1000) target image, which is the case with any traversal, and figure out the result pixels from two source images. In a structural language we could just use mutation and go through that (50, 50) region of a larger image and update those pixels only, but in case of a pure functional language like Haskell we cannot safely do that without making a copy of a larger image, although there is a way to do it in `hip` using mutations with `MArray` class.
Luckily fusion helps us with avoiding creating intermediate images, so at the end it's not such huge of an issue.
I am of course open to ideas. I put together a branch with an alternative `superimpose` implementation (which turns out to be slower) and benchmark that you can use to try some different approaches: `benchmarks/Superimpose.hs`. Just run it as `$ stack bench hip:bench:superimpose-benchmarks`

**Comment by silky** [comment]
thanks heaps for that!

i noticed the slowness when making this - https://github.com/silky/rezoomer

with a small image (< 200 kb) it runs in the tens of seconds, and with a larger image (~1 meg) it takes 3 or 4 minutes!

```
09:26 AM noon ∈ rezoomer@master>l ~/Pictures/15GERGOSZINYOVA.jpg 
-rw-rw-r-- 1 noon noon 136K Dec  5 10:47 /home/noon/Pictures/15GERGOSZINYOVA.jpg

09:25 AM noon ∈ rezoomer@master>time stack exec -- rezoomer --size 50 --inImage ~/Pictures/15GERGOSZINYOVA.jpg --outImage images/out.jpg 
stack exec -- rezoomer --size 50 --inImage ~/Pictures/15GERGOSZINYOVA.jpg
21.22s user 0.11s system 100% cpu 21.307 total


09:30 AM noon ∈ rezoomer@master>l ~/Pictures/blue.jpg
-rw-rw-r-- 1 noon noon 1.1M Dec  5 10:47 /home/noon/Pictures/blue.jpg

09:26 AM noon ∈ rezoomer@master>time stack exec -- rezoomer --size 50 --inImage ~/Pictures/blue.jpg --outImage images/out.jpg 
stack exec -- rezoomer --size 50 --inImage ~/Pictures/blue.jpg --outImage   
213.58s user 1.38s system 99% cpu 3:35.06 total
```

running with profiling, it is spending over half it's time in `traverse2`:

```
	Mon Jan 30 21:20 2017 Time and Allocation Profiling Report  (Final)

	   rezoomer +RTS -p -RTS --size 50 --inImage /home/noon/Pictures/15GERGOSZINYOVA.jpg --outImage images/out.jpg

	total time  =       44.19 secs   (44187 ticks @ 1000 us, 1 processor)
	total alloc = 50,148,611,664 bytes  (excludes profiling overheads)

COST CENTRE                  MODULE                                SRC                                                            %time %alloc

traverse2                    Graphics.Image.Interface.Repa.Generic src/Graphics/Image/Interface/Repa/Generic.hs:(242,3)-(243,82)   42.0   71.6
traverse2                    Graphics.Image.Interface.Repa.Unboxed src/Graphics/Image/Interface/Repa/Unboxed.hs:170:3-83           12.6    0.0
index                        Data.Array.Repa.Repr.Delayed          Data/Array/Repa/Repr/Delayed.hs:31:2-39                          5.2    0.0
basicUnsafeIndexM            Data.Vector.Storable                  Data/Vector/Storable.hs:(220,3)-(223,53)                         3.3    4.1
basicUnsafeWrite             Data.Vector.Storable.Mutable          Data/Vector/Storable/Mutable.hs:(138,3)-(140,49)                 2.6    2.2
basicUnsafeRead              Data.Vector.Storable.Mutable          Data/Vector/Storable/Mutable.hs:(133,3)-(135,41)                 2.3    4.0
fastDctLibJpeg.firstPass     Codec.Picture.Jpg.FastDct             src/Codec/Picture/Jpg/FastDct.hs:(79,9)-(144,39)                 2.1    0.7
fastDctLibJpeg.secondPass    Codec.Picture.Jpg.FastDct             src/Codec/Picture/Jpg/FastDct.hs:(150,9)-(214,36)                2.0    0.7
serializeMacroBlock.encodeAc Codec.Picture.Jpg                     src/Codec/Picture/Jpg.hs:(684,9)-(695,81)                        1.4    0.5
idctCol                      Codec.Picture.Jpg.FastIdct            src/Codec/Picture/Jpg/FastIdct.hs:(143,1)-(204,76)               1.3    0.1
primitive                    Control.Monad.Primitive               Control/Monad/Primitive.hs:143:3-16                              1.3    0.2
convertPixel                 Codec.Picture.Types                   src/Codec/Picture/Types.hs:(2014,5)-(2022,50)                    1.1    0.7
```

so yeah.

i'm not sure if we need to go to mutability to speed it up, or alternatively i'm not sure if i've just made some serious error in my code that causes it to be so slow, but i do think that this kind of thing should be much faster.

thanks for your prompt responses!

**Comment by lehins** [comment]
`superimpose` is already as fast as it can get. Performance issue was hiding somewhere else.
See silky/rezoomer#4 for resolution.

**Comment by silky** [comment]
thanks again!
